name: et
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  - pip:
    - numpy
    - requests
    - pyinstaller
    - onnxruntime-gpu
    - tf2onnx
    - opencv-python
    - python-osc
    - tensorflow-cpu
    - serial
    - colorama
