name: et
channels:
  - conda-forge
dependencies:
  - python =3.11
  - numpy=1.26.4
  - opencv
  - requests
  - onnxruntime
  - pip

  - pip:
      - tf2onnx
      - python-osc
      - tensorflow-cpu
      - pyinstaller
      - serial
      - colorama
